### ISSUE TITLE
     Install marbles chaincode on the Peer 1 failed on kubernetes cluster

### ISSUE THREAD

**Issue by knagware9** [mrshah-at-work/fabric-kubernetes#1] opened 2017-09-02 15:10 UTC
Hi,
Install_chaincode.sh failed due to peer key not found,,I think script not deploying to cluster ,,its going to deploy localy...could you please help..I am gettting below error

hertzpoc@hertzpoc-VirtualBox:~/fabric-kubernetes/marbles$ sudo ./install_chaincode.sh
info: Using default config file marbles_cs.json
info: Loaded config file /home/hertzpoc/fabric-kubernetes/marbles/marbles/config/marbles_cs.json
info: Loaded creds file /home/hertzpoc/fabric-kubernetes/marbles/marbles/config/blockchain_cs.json
---------------------------------------
info: Lets install some chaincode - marbles v1.0
---------------------------------------
info: First we enroll
/home/hertzpoc/fabric-kubernetes/marbles/marbles/utils/helper.js:78
				throw new Error('Peer key not found.');
				^

Error: Peer key not found.
    at Object.helper.getPeersUrl (/home/hertzpoc/fabric-kubernetes/marbles/marbles/utils/helper.js:78:11)
    at Object.helper.makeEnrollmentOptionsUsingCert (/home/hertzpoc/fabric-kubernetes/marbles/marbles/utils/helper.js:538:23)
    at Object.<anonymous> (/home/hertzpoc/fabric-kubernetes/marbles/marbles/scripts/install_chaincode1.js:31:32)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)

**Comment by mrshah-at-work** [comment] 2017-09-05 12:41
@knagware9 this looks like a duplicate of https://github.com/IBM-Blockchain/ibm-container-service/issues/5. I am closing this. Feel free to reopen this issue.

**Closed as completed by mrshah-at-work** 2017-09-05 12:41 UTC
